### ISSUE TITLE
Allow IP ranges as whitelist filter?

### ISSUE THREAD

**Issue by janhoogeveen** [flawyte/static-auth#1]
Hi @flawyte!

Would you be willing to accept a PR that adds the ability to whitelist IP addresses from basic auth? We use basic auth on development/staging servers quite often and use IP whitelists to grant access to anyone working from our office.

A while ago I wrote [a blogpost](https://janhoogeveen.eu/blog/whitelisting-access-to-now-serverless-deployments) about how one could approach that with a custom hooks in Next.js servers. I assume it's would be trivial for me to add it to this package.

**Comment by hormesiel** [comment]
> Transferring this issue to @flawyte/static-auth since it's the package this request is related to.

Hi @janhoogeveen!

Thanks for your suggestion. However I don't think it's needed to pass the `request` object to the callback validator function if you want to add IP whitelisting ‒ just create a thin wrapper around the return of value of the `protect()` method :

Before :
```js
const protect = require('static-auth');

module.exports = protect(
  '/admin',
  (user, pass) => (user === 'admin' && pass === 'admin')
);
```

After :
```js
// Basic authentication & file serving
const protect = require('static-auth');
const authAndServe = protect(
  '/admin',
  (user, pass) => (user == 'admin' && pass == 'admin')
);


// IP whitelisting
const allowedIps = ['x.x.x.x'];
const ipIsAllowed = req => {
  const ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
  return allowedIps.includes(ip);
};

// Our app
module.exports = (req, res) => {
  // If ip is not allowed, no need to go further
  if (!ipIsAllowed(req)) {
    res.statusCode = 401;
    res.end('401 Unauthorized');
    return;
  }

  // Else, ask for authentication and serve the requested file
  authAndServe(req, res);
};
```

Let me know if that works for you!

**Comment by janhoogeveen** [comment]
That actually seems like a better approach. Thanks!
